version: "3"

services:
  chat-server:
    image: gwonsooche/chat-server:latest
    ports:
      - "3002:3002"
    restart: on-failure
    depends_on:
      rabbitmq-server:
        condition: service_healthy
  
  rabbitmq-server:
    image: "rabbitmq:3.12-management"
    healthcheck:
      test: rabbitmq-diagnostics -q ping

  log-service:
    image: gwonsooche/log-service:latest
    restart: on-failure
    depends_on:
      rabbitmq-server:
        condition: service_healthy
